Projekt zespołowy/movie-review/movie_review/urls.py
from django.contrib import admin
from django.urls import path,include
#extra settings
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movie.urls')),
    path('', include('user.urls')),
]

Projekt zespołowy/movie-review/user/urls.py
from django.urls import path
from .views import EditProfile, Signup, UserProfile, MyTokenObtainPairView, SignupView, UserProfileView, MoviesWatched, SeriesWatched, add_review, movie_details
from django.contrib.auth import views as userViews
from rest_framework_simplejwt.views import (
    TokenRefreshView
)

urlpatterns = [
    path('login/', userViews.LoginView.as_view(template_name='user/login.html',next_page='landing'), name='login'),
    path('logout/', userViews.LogoutView.as_view(next_page='landing'), name='logout'),
    path('profile/<username>/', UserProfile, name='profile'),
    path('profile/edit', EditProfile, name='edit-profile'),
    path('signup/', Signup, name='register'),

    path('api/movies_watched/<username>/', MoviesWatched, name='movies_watched'),
    path('api/series_watched/<username>/', SeriesWatched, name='series_watched'),

    path('api/post/', SignupView.as_view(), name='signup'),
    path('api/profile/', UserProfileView.as_view(), name='profile'),
    
    path('api/token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    path('api/add_review/', add_review, name='add_review'),
     path('api/movie_details/<str:imdbID>/', movie_details, name='movie_details'),
    
]

Projekt zespołowy/movie-review/movie/forms.py
from django import forms
from movie.models import Review, RATE_CHOICES

class RateForm (forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={'required':'False'}))
    rate = forms.ChoiceField(choices=RATE_CHOICES, widget=forms.Select(), required=True)

    class Meta:
        model = Review
        fields = ('text', 'rate')
        

Projekt zespołowy/movie-review/movie_review/templates/MovieDetailsPage.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
<div class-"movie-info-container" style="background-color: #c9d1d5; min-height: 100vh; overflow: hidden;">
  <div class="row">
    <h1 class="text-center pt-5">{{movie_data.Title}}</h1>
  </div>
  <div class="container" id="datadisp">
    <div class="row">
      <div class="col-md-4">
        {%if our_db is True %}
          <img src=" {{ movie_data.Poster_url }} " class="card-img-top h-80vh" style="height: 70vh;" />
        {% else %}
          <img src=" {{ movie_data.Poster }} " class="card-img-top" style="height: 70vh;"/>
        {%endif%}
      </div>
      <div class="col-md-8 d-flex">
      <div class="col-md-2">
        <h6 class="mt-3"><b>Released : </b></h6>
        <h6><b>Type : </b></h6>
        <h6><b>Runtime : </b></h6>
        <h6><b>Genre :</b></h6>
        <h6><b>Language : </b></h6>
        <h6><b>Country : </b></h6>
        <h6><b>Actors :</b></h6>
        <h6><b>Writer :</b></h6>
        <h6><b>Director : </b></h6>
        <h6><b>Awards : </b></h6>
        <h6><b>Rating : </b></h6>
        <h6><b>Plot : </b></h6>
        <br>
        <h6><b>Review : </b></h6>
      </div>
      <div class="col-md-10">
        <h6 class="mt-3"><b>{{movie_data.Year}}</b></h6>
        <h6><b>{{movie_data.Type}}</b></h6>
        <h6><b>{{movie_data.Runtime}}</b></h6>
      
        <h6>
        {%if our_db is True %}
          {% for genre in movie_data.Genre.all %}
            <b><a href="{{ genre.get_absolute_url }}" style="text-decoration:none;">{{ genre }}</a>,</b>
          {% endfor %}
        {% else %}
          <b>{{movie_data.Genre}}</b>
        {%endif%}
        </h6>
        
        <h6><b>{{movie_data.Language}}</b></h6>
        <h6><b>{{movie_data.Country}}</b></h6>
      
        
        <h6><b>{{movie_data.Actors}}</b></h6>
      
        <h6><b>{{movie_data.Writer}}</b></h6>
        <h6><b>{{movie_data.Director}}</b></h6>
        <h6><b>{{movie_data.Awards}}</b></h6>
        <h6><b>{{movie_data.Rated}}</b></h6>
        <h6><b>{{movie_data.Plot}}</b></h6>
                  <br>
        {% if our_db is True %}
          <h6><b>Rated {{ reviews_avg.rate__avg }}/5 by {{ reviews_count }} people</b></h6>
          {% for movie in movie_data.Ratings.all %} 
            {% if movie.source == 'Internet Movie Database' %}
              <h6><b>{{ movie.rating }} (IMDB)</b></h6>
            {% elif movie.source == 'Rotten Tomatoes' %}
              <h6><b>{{ movie.rating }} ({{ movie.source }})</b></h6>
            {% else %}
              <h6><b>{{ movie.rating }} ({{ movie.source }})</b></h6>
            {% endif %}        
          {% endfor %}  
        {% else %}
          <h6><b>{{ movie_data.Ratings.0.Value }}({{ movie_data.Ratings.0.Source }})</b></h6>
          <h6><b>{{ movie_data.Ratings.1.Value }}({{ movie_data.Ratings.1.Source }})</b></h6>
          <h6><b>{{ movie_data.Ratings.2.Value }}({{ movie_data.Ratings.2.Source }})</b></h6>
        {% endif %}
         <div class="pt-3">
          <!-- <div class="rate-dropdown">
            <a style="text-decoration:none;"class="login-button" href="{%url 'watchlist' movie_data.imdbID %}">Rate</a>
            <div class="rate-dropdown-link">
              <a href="{%url 'profile' user.username %}">Profile</a>
              <a href="{% url 'edit-profile' %}">Edit profile</a>
              <a href="{% url 'logout' %}">Logout</a>
            </div>
          </div> --> 
          {%if our_db is False or reviewed is False%}
            <a  style="text-decoration:none;"class="login-button" href="{% url 'rate-movie' movie_data.imdbID %}">Rate Movie</a>
          {%endif%}
            <a  style="text-decoration:none;"class="login-button" href="{%url 'watchlist' movie_data.imdbID %}">Add to Watchlist</a>
          <a  style="text-decoration:none;"class="login-button" href="{%url 'watched_movies' movie_data.imdbID %}">Add to Watched</a>
        </div>
        
      </div>
      </div>
    </div>
  </div>
  <div class="background" style="background-image: linear-gradient(to left top, #55c2c3, #3397a8, #1f6e87, #154762, #0c243c);"></div>
</div>
      {%if our_db is True%}
      {%if reviews_count == 0 %}
      <div class-"movie-info-container" style="background-color: #c9d1d5; min-height: 100vh; overflow-x: hidden;">
        <h1 class="text-center pt-5">Reviews</h1>
      <h1 class="text-center pt-5">No reviews to show :(</h1>

      </div>
      {%else%}


<div class-"movie-info-container" style="background-color: #c9d1d5; min-height: 100vh; overflow-x: hidden;">
    <h1 class="text-center pt-5">Reviews</h1>
  <div class="row d-flex justify-content-center">
    <div class="col-md-8 col-lg-6">
      <div class="card shadow-0 border" style="background-color: #f0f2f5;">
        <div class="card-body p-4">
        {% for review in reviews %}
          <div class="card mb-4">
            <div class="card-body">
              <p>{{review.text}}</p>
              <div class="d-flex justify-content-between">
                <div class="d-flex flex-row align-items-center">
                  {%if review.user.profile.picture%}
                  <img src="{{review.user.profile.picture.url}}" alt="avatar" width="25" height="25" />
                  {%else%}
                  <img src="{%static 'img/blank.jpg' %}" alt="avatar" width="25"height="25" />
                  {%endif%}
                  <p class="small mb-0 ms-2"><a href="{% url 'profile' review.user.username %}" style="text-decoration:none;">{{review.user.username}}</a> on {{review.date}} </p>
                </div>
                <div class="d-flex flex-row align-items-center">
                  <p class="small text-muted mb-0">Rated {{review.rate}} out of 5</p>
                </div>
              </div>
            </div>
          </div>
        {%endfor%}
          

        </div>
      </div>
    </div>
  </div>
</div>
        {%endif%}
        {%endif%}

{%endblock%}

Projekt zespołowy/movie-review/movie_review/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie Review</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.rtl.min.css"
        integrity="sha384-DOXMLfHhQkvFFp+rWTZwVlPVqdIhpDVYT9csOnHSgWQWPX0v5MCGtjCJbY6ERspU" crossorigin="anonymous">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/png">
    <link rel="stylesheet" href="{% static 'css/landing.css' %}">
</head>
<body>
    <nav>
        <a class="logo-link" href="{%url 'landing' %}"><img class="logo" src="{% static '/img/text.png' %}" title="Logo" width="75"></a>
        {%if user.is_authenticated %}
            <div class="dropdown">
                <a href="#" class="navbar-link">{{user.username}}<i class="fa fa-caret-down" style="padding-left:10px;"></i></a>
                <div class="dropcontent">
                    <a href="{%url 'profile' user.username %}">Profile</a>
                    <a href="{% url 'edit-profile' %}">Edit profile</a>
                    <a href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        {%else%}
        <a href="{% url 'login' %}" class="navbar-signin-link">Sign in</a>
        {%endif%}
    </nav>
    {%block content%}
    {%endblock%}
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</body>
</html>

Projekt zespołowy/movie-review/movie_review/templates/genre.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
<h1 class="movie-list-title" style="padding-top:4rem; text-align:center;">Genre: {{genre_slug}}</h1>
<div class="search-movie-container">
    {%for movie in movie_data%}
    <div class="search-movie-card">
        <div class="search-movie-image-div">
            <img src="{{movie.Poster_url}}">
            <div class="search-movie-title">
                <h1>{{movie.Title}}</h1>
                <h6>{{movie.Type}}</h6>
            </div>
            <div class="search-movie-des">
                <p>{{movie.Year}}</p>
                <div class="movie-info-link">
                    <a style="text-decoration:none;" href="{% url 'movie-details' movie.imdbID %}"
                        class="login-button">Info</a>
                </div>
            </div>
        </div>
    </div>
    {%endfor%}
</div>
{%endblock%}

Projekt zespołowy/movie-review/movie_review/templates/landing.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
<div class="home">
    <!--
        <div class="text">
        <p class="landing-text" data-text="FIND&#160;YOUR&#160;FAVORITE&#160;MOVIE">FIND YOUR FAVORITE MOVIE</p>
    </div>
    --> 
    <div class="search">
        <form method="GET" action="{% url 'search' %}" class="search-bar">
            <input class="input" type="search" placeholder="Search any movie" aria-label="Search" name="q"
                id="query" value="{{request.GET.q}}">
            <button class="button" name="action" type="submit" >Search</button>
        </form>
    </div>
    <!--
    <div class="genre-dropdown">
        <a href="#" class="genre-link login-button">Search  by Genre<i class="fa fa-caret-down" style="padding-left:10px;"></i></a>
        <div class="genre-dropcontent">
            {%for genre in genre_list%}
                <a class="login-button genre-button" href="{{ genre.get_absolute_url }}">{{genre}}</a>
            {%endfor%}
        </div>
    </div>
    --> 
    <div class="background"><img src="{% static '/img/icon.jpg' %}" alt=""></div>
</div>
{%endblock%}

Projekt zespołowy/movie-review/movie_review/templates/rate.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
<form method="POST" action="" class="rate-form">
    {%csrf_token%}
    <select name="rate" id="id_rate" class="login-button">
            <div class="rate-dropdown-link">
        <option value="" selected disabled>Rate</option>
        <option value="1">1-Trash</option>
        <option value="2">2-Terrible</option>
        <option value="3">3-OK</option>
        <option value="4">4-Good</option>
        <option value="5">5-Perfect</option>
        </div>
    </select>
    <textarea name="text" id="id_text"></textarea>
    {% if form.errors %}
        {{form.errors}}
    {%endif%}
    <div class="button">
        <input type="submit" value="Add Review" class="login-button">
    </div>
</form>
{%endblock%}

Projekt zespołowy/movie-review/movie_review/templates/search.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
<div class="outer-search-container"></div>
<h1 class="movie-list-title" style="padding-top:4rem; text-align:center;">Results for:{{query}}</h1>
<div class="search-movie-container">
    {%for movie in movie_data.Search%}
        <div class="search-movie-card">
            <div class="search-movie-image-div">
                {% if movie.Poster == 'N/A' %}
                <img src="{% static 'img/no_poster.jpg' %}">
                {% else %}
                <img src="{{ movie.Poster }}">
                {% endif %}
                <div class="search-movie-title">
                    <h1>{{movie.Title}}</h1>
                    <h6>{{movie.Type}}</h6>
                </div>
                <div class="search-movie-des">
                    <p>{{movie.Year}}</p>
                    <div class="movie-info-link">
                        <a style="text-decoration:none;"  href="{% url 'movie-details' movie.imdbID %}" class="login-button">Info</a>
                    </div>
                </div>
            </div>
        </div>
    {%endfor%}
</div>
{%endblock%}